site_name: My Fab Academy Journey
theme:
  name: material
  features:
    - navigation.tabs  # Adds the top nav bar you asked for
nav:
  - Home: index.md
  - Assignments:
      - Week 1: folder/week01.md
      - Week 2: folder/week02.md
